"""asdf

Revision ID: 7f975ea06baa
Revises: 
Create Date: 2021-08-25 17:05:15.183645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f975ea06baa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lake',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temp_lake', sa.Float(), precision=3, scale=2, nullable=False, ),
    sa.Column('temp_air', sa.Float(), nullable=False, max_length=5),
    sa.Column('humidity_air', sa.Float(), nullable=False, max_length=5),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lake')
    # ### end Alembic commands ###
